version: "3.9"

# IMPORTANT: Copy the contents of this file to docker-compose-prod.yml
#            then carefully review and change the environment variables
#            appropriately!

# NOTE: Lines with __REPLACE_ME__ need to be replaced appropriately.

services:
  web:
    build: .
    expose:
      - 8000
    command: gunicorn fp_showcase.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-@k!m0yes_n)i@h(hr8wg##i&xf#vxkx+aid2!sv-h2)zv25=%$$"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
      - "DJANGO_SECURE_PROXY_SSL_HEADER=True"
      - "DJANGO_ALLOWED_HOSTS=__REPLACE_ME__"
      - "VIRTUAL_HOST=__REPLACE_ME__"
      - "VIRTUAL_PORT=8000"
      - "LETSENCRYPT_HOST=__REPLACE_ME__"
      - "CSRF_TRUSTED_ORIGINS=__REPLACE_ME__"
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  acme-companion:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    environment:
      - "DEFAULT_EMAIL=__REPLACE_ME__"
      - "ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
    depends_on:
      - nginx-proxy
volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: