# Generated by Django 5.1.4 on 2025-01-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_description',
            field=models.TextField(blank=True, verbose_name='profile description'),
        ),
    ]
