# Generated by Django 5.1.4 on 2025-01-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='slug', unique=True, verbose_name='slug'),
        ),
    ]
