# Generated by Django 5.1.4 on 2025-01-02 23:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=accounts.models.create_ulid_filename, verbose_name='profile picture'),
        ),
    ]
