# Generated by Django 5.1.4 on 2025-01-02 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('creator', models.CharField(blank=True, max_length=200)),
                ('nib_size', models.CharField(blank=True, max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchase_location', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('favorite', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
