# Generated by Django 5.1.4 on 2025-01-03 04:38

import django.db.models.deletion
import util.ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=util.ulid.create_ulid_filename, verbose_name='pen image')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pens.pen')),
            ],
        ),
    ]
