# Generated by Django 5.1.4 on 2025-01-03 20:51

import util.ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=util.ulid.create_ulid_filename),
        ),
    ]
